api_platform:
    title: Altered Core API
    version: 1.0.0
    eager_loading:
        force_eager: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Accept', 'Accept-Language']
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 1000
    formats:
        json: ['application/json']
    docs_formats:
        json: ['application/json']
