security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        metrics:
            pattern: ^/metrics
            security: false
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        admin:
            pattern: ^/admin
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                default_target_path: admin_effects_index
            logout:
                path: admin_logout
                target: admin_login
        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/cards, roles: PUBLIC_ACCESS }
        - { path: ^/api/sets, roles: PUBLIC_ACCESS }
        - { path: ^/api/card_groups, roles: PUBLIC_ACCESS }
        - { path: ^/api/factions, roles: PUBLIC_ACCESS }
        - { path: ^/api/card_types, roles: PUBLIC_ACCESS }
        - { path: ^/api/card_sub_types, roles: PUBLIC_ACCESS }
        - { path: ^/api/main_effects, roles: PUBLIC_ACCESS }
        - { path: ^/api/ability_triggers, roles: PUBLIC_ACCESS }
        - { path: ^/api/ability_conditions, roles: PUBLIC_ACCESS }
        - { path: ^/api/ability_effects, roles: PUBLIC_ACCESS }
        - { path: ^/api/keywords, roles: PUBLIC_ACCESS }
        - { path: ^/api/effect-chain, roles: PUBLIC_ACCESS }
        - { path: ^/api/triggers, roles: PUBLIC_ACCESS }
        - { path: ^/api/conditions, roles: PUBLIC_ACCESS }
        - { path: ^/api/effects, roles: PUBLIC_ACCESS }
        - { path: ^/query, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
